services:
  - type: web
    name: instagram-checker-backend
    env: node
    region: singapore
    plan: free
    buildCommand: "./build.sh && npm install"
    startCommand: "node Server.js"
    envVars:
      NODE_ENV: "production"
